ptu_pan_position_controller:
  joint: ptu_pan
  pid:
    d: 0
    i: 0
    p: 10
  type: position_controllers/JointPositionController
ptu_tilt_position_controller:
  joint: ptu_tilt
  pid:
    d: 0
    i: 0
    p: 10
  type: position_controllers/JointPositionController
    

#/gazebo_ros_control:
#  pid_gains:
#    ptu_pan:
#      p: 10
#      i: 0 
#      d: 0
#    ptu_tilt:
#      p: 10
#      i: 0 
#      d: 0
